// Code generated by gen-lambda-handlers from events.json. DO NOT EDIT. 수정하지 마세요.

package main

import (
	"context"

	"github.com/aws/aws-lambda-go/lambda"

	"server/internal/app/notification"
)

type Request struct{}

type Response struct {
	OK bool `json:"ok"`
}

func handler(ctx context.Context, _ Request) (Response, error) {
	var repo notification.Repository
	var bus notification.EventBus
	svc := notification.NewService(repo, bus)

	if err := svc.Created(ctx, notification.Command{}); err != nil {
		return Response{OK: false}, err
	}
	return Response{OK: true}, nil
}

func main() {
	lambda.Start(handler)
}

