export const endpoints = {
  auth: {
    signup: '/user/auth/google/signup',
    login: '/user/auth/google/login',
    refresh: '/user/auth/refresh',
    me: '/user/me',
  },
  sessions: {
    list: '/sessions',
    detail: (id) => `/sessions/${id}`,
    messages: (id) => `/sessions/${id}/messages`,
    send: (id) => `/sessions/${id}/messages`,
  },
  sentinel: {
    status: '/sentinel/control/status',
    alerts: '/sentinel/control/alerts',
    logs: '/sentinel/control/logs',
    tokenUsage: '/sentinel/control/token-usage',
    taskDone: '/sentinel/control/task-done',
    reset: '/sentinel/control/reset',
    resume: '/sentinel/control/resume',
  },
  maps: {
    initialize: '/maps/task-map/initialize',
  },
  ai: {
    analyzeLogs: '/ai/analyze-logs',
    generatePlan: '/ai/generate-plan',
    convertToTree: '/ai/convert-to-tree',
    summarize: '/ai/summarize',
    generateFrontier: '/ai/generate-frontier',
    chat: '/ai/chat',
  },
  plans: {
    list: '/plans',
    get: (id) => `/plans/${id}`,
    save: '/plans',
    remove: (id) => `/plans/${id}`,
    getTree: (id) => `/plans/${id}/tree`,
    saveTree: (id) => `/plans/${id}/tree`,
  },
  tracks: {
    get: (planId) => `/tracks/${planId}`,
    save: (planId) => `/tracks/${planId}`,
    updateNodeStatus: (planId, nodeUid) => `/tracks/${planId}/nodes/${nodeUid}/status`,
    appendNodeLog: (planId, nodeUid) => `/tracks/${planId}/nodes/${nodeUid}/log`,
    getNodeLogs: (planId, nodeUid) => `/tracks/${planId}/nodes/${nodeUid}/logs`,
  },
  run: {
    start: '/run/start',
    addAgent: '/run/add-agent',
    stopAgent: '/run/stop-agent',
    agents: '/run/agents',
    tasks: '/run/tasks',
    logs: '/run/logs',
    resumable: '/run/resumable',
    progress: '/run/progress',
    agentLogs: (agentId) => `/run/agents/${agentId}/logs`,
    pauseAll: '/run/pause-all',
    resumeAll: '/run/resume-all',
    strategyMeetingStart: '/run/strategy-meeting/start',
    strategyMeetingStatus: '/run/strategy-meeting/status',
  },
  jobs: {
    list: '/jobs',
    detail: (id) => `/jobs/${id}`,
    retry: (id) => `/jobs/${id}/retry`,
  },
};
