// Code generated by gen-lambda-handlers from events.json. DO NOT EDIT. 수정하지 마세요.

package main

import (
	"context"

	"github.com/aws/aws-lambda-go/lambda"

	"server/internal/app/task"
)

type Request struct{}

type Response struct {
	OK bool `json:"ok"`
}

func handler(ctx context.Context, _ Request) (Response, error) {
	var repo task.Repository
	var bus task.EventBus
	var planner task.ContextPlanner
	svc := task.NewService(repo, bus, planner)

	if err := svc.HardStop(ctx, task.StatusCommand{}); err != nil {
		return Response{OK: false}, err
	}
	return Response{OK: true}, nil
}

func main() {
	lambda.Start(handler)
}

